import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F172A" },
  content: { padding: 28, maxWidth: 1100, width: "100%", alignSelf: "center" },
  header: { marginBottom: 32 },
  greeting: {
    fontSize: 13,
    fontWeight: "600",
    color: "#3B82F6",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#F8FAFC",
    letterSpacing: -0.5,
  },
  subtitle: { fontSize: 15, color: "#475569", marginTop: 4 },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 32,
  },
  statCard: {
    flex: 1,
    minWidth: 180,
    backgroundColor: "rgba(30,41,59,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 20,
  },
  statIcon: { fontSize: 28, marginBottom: 12 },
  statValue: {
    fontSize: 32,
    fontWeight: "800",
    color: "#F8FAFC",
    marginBottom: 4,
  },
  statLabel: { fontSize: 13, color: "#64748B", fontWeight: "500" },
  statSub: { fontSize: 11, color: "#334155", marginTop: 2 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#3B82F6",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  actionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 32,
  },
  actionCard: {
    flex: 1,
    minWidth: 200,
    backgroundColor: "rgba(30,41,59,0.6)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 20,
  },
  actionCardPrimary: {
    borderColor: "rgba(37,99,235,0.3)",
    backgroundColor: "rgba(37,99,235,0.08)",
  },
  actionIcon: { fontSize: 28, marginBottom: 12 },
  actionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#F1F5F9",
    marginBottom: 4,
  },
  actionDesc: {
    fontSize: 13,
    color: "#64748B",
    lineHeight: 18,
    marginBottom: 16,
  },
  actionButton: {
    backgroundColor: "#2563EB",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  actionButtonSecondary: {
    backgroundColor: "rgba(30,41,59,0.8)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  actionButtonText: { fontSize: 13, fontWeight: "600", color: "#FFFFFF" },
  actionButtonTextSecondary: { color: "#94A3B8" },
  recentSection: {
    backgroundColor: "rgba(30,41,59,0.5)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  recentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  recentTitle: { fontSize: 16, fontWeight: "700", color: "#F1F5F9" },
  viewAllText: { fontSize: 13, color: "#3B82F6", fontWeight: "600" },
  projectRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
    gap: 12,
  },
  projectDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#3B82F6",
  },
  projectDotMobile: { backgroundColor: "#8B5CF6" },
  projectDotBackend: { backgroundColor: "#10B981" },
  projectInfo: { flex: 1 },
  projectTitle: { fontSize: 14, fontWeight: "600", color: "#F1F5F9" },
  projectMeta: { fontSize: 12, color: "#475569", marginTop: 1 },
  featuredBadge: {
    backgroundColor: "rgba(234,179,8,0.1)",
    borderWidth: 1,
    borderColor: "rgba(234,179,8,0.2)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  featuredBadgeText: { fontSize: 11, fontWeight: "600", color: "#FCD34D" },
  emptyText: {
    fontSize: 14,
    color: "#475569",
    textAlign: "center",
    paddingVertical: 24,
  },
  resumeStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
  },
  resumeStatusDot: { width: 10, height: 10, borderRadius: 5 },
  resumeStatusText: { fontSize: 14, color: "#94A3B8" },
});
