import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, flexDirection: "row", backgroundColor: "#0F172A" },
  sidebar: {
    width: 240,
    backgroundColor: "rgba(15,23,42,0.95)",
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.06)",
    paddingVertical: 24,
    paddingHorizontal: 16,
    justifyContent: "flex-start",
  },
  sidebarLogoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    marginBottom: 32,
  },
  sidebarLogoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#3B82F6",
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#F8FAFC",
    letterSpacing: -0.3,
  },
  sidebarLinks: { flex: 1, gap: 2 },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.2)",
    backgroundColor: "rgba(239,68,68,0.05)",
  },
  logoutText: { fontSize: 14, fontWeight: "600", color: "#EF4444" },
  mainArea: { flex: 1, backgroundColor: "#0F172A" },
  header: {
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(15,23,42,0.9)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { fontSize: 18, fontWeight: "700", color: "#F1F5F9" },
  headerBadge: {
    backgroundColor: "rgba(34,197,94,0.1)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.2)",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  headerBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22C55E",
  },
  headerBadgeText: { fontSize: 12, fontWeight: "600", color: "#4ADE80" },
  content: { flex: 1 },
  contentInner: { padding: 28, flexGrow: 1 },
});
