import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, flexDirection: "row", backgroundColor: "#060B18" },
  sidebar: {
    width: 248,
    backgroundColor: "rgba(10,14,30,0.98)",
    borderRightWidth: 1,
    borderRightColor: "rgba(99,102,241,0.1)",
    paddingVertical: 28,
    paddingHorizontal: 16,
    justifyContent: "flex-start",
  },
  sidebarLogoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    marginBottom: 36,
  },
  sidebarLogoDot: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#6366F1",
  },
  sidebarTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#F1F5F9",
    letterSpacing: -0.4,
  },
  sidebarLinks: { flex: 1, gap: 2 },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 10,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.2)",
    backgroundColor: "rgba(239,68,68,0.05)",
  },
  logoutText: { fontSize: 14, fontWeight: "700", color: "#F87171" },
  mainArea: { flex: 1, backgroundColor: "#060B18" },
  header: {
    paddingHorizontal: 32,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(99,102,241,0.08)",
    backgroundColor: "rgba(6,11,24,0.95)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#F1F5F9",
    letterSpacing: -0.4,
  },
  headerBadge: {
    backgroundColor: "rgba(34,197,94,0.08)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.2)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  headerBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22C55E",
  },
  headerBadgeText: { fontSize: 12, fontWeight: "700", color: "#4ADE80" },
  content: { flex: 1 },
  contentInner: { padding: 32, flexGrow: 1 },
});
