import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
    backgroundColor: "rgba(10,14,30,0.9)",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(99,102,241,0.08)",
  },
  headerTitle: { fontSize: 14, fontWeight: "700", color: "#94A3B8" },
  headerBadge: {
    backgroundColor: "rgba(99,102,241,0.12)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.25)",
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  headerBadgeText: { fontSize: 11, fontWeight: "700", color: "#A5B4FC" },
  iframeWrapper: {
    width: "100%" as unknown as number,
    height: 500,
    backgroundColor: "#000",
  },
  fallback: { padding: 36, alignItems: "center", gap: 16 },
  fallbackIcon: { fontSize: 40 },
  fallbackTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#F1F5F9",
    textAlign: "center",
  },
  fallbackText: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 22,
  },
  fallbackButton: {
    backgroundColor: "#6366F1",
    paddingHorizontal: 22,
    paddingVertical: 11,
    borderRadius: 10,
    marginTop: 8,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  fallbackButtonText: { fontSize: 14, fontWeight: "700", color: "#FFFFFF" },
});
