import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {},
  item: { flexDirection: "row", marginBottom: 32 },
  indicator: { alignItems: "center", marginRight: 20, width: 20 },
  dotWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(59,130,246,0.15)",
    borderWidth: 2,
    borderColor: "#3B82F6",
    alignItems: "center",
    justifyContent: "center",
  },
  dotWrapperEducation: {
    borderColor: "#8B5CF6",
    backgroundColor: "rgba(139,92,246,0.15)",
  },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#3B82F6" },
  dotEducation: { backgroundColor: "#8B5CF6" },
  line: {
    width: 2,
    flex: 1,
    backgroundColor: "rgba(59,130,246,0.15)",
    marginTop: 4,
    marginBottom: -8,
  },
  card: {
    flex: 1,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 4,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 6,
    flexWrap: "wrap",
    gap: 8,
  },
  title: { fontSize: 17, fontWeight: "700", color: "#F1F5F9", flex: 1 },
  dateBadge: {
    backgroundColor: "rgba(59,130,246,0.1)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  dateBadgeEducation: {
    backgroundColor: "rgba(139,92,246,0.1)",
    borderColor: "rgba(139,92,246,0.2)",
  },
  date: { fontSize: 12, color: "#93C5FD", fontWeight: "500" },
  dateEducation: { color: "#C4B5FD" },
  organization: {
    fontSize: 14,
    fontWeight: "600",
    color: "#3B82F6",
    marginBottom: 4,
  },
  organizationEducation: { color: "#8B5CF6" },
  location: { fontSize: 12, color: "#475569", marginBottom: 10 },
  description: {
    fontSize: 14,
    color: "#94A3B8",
    lineHeight: 22,
    marginBottom: 12,
  },
  highlights: { gap: 6 },
  highlight: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  highlightBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#3B82F6",
    marginTop: 7,
    flexShrink: 0,
  },
  highlightBulletEducation: { backgroundColor: "#8B5CF6" },
  highlightText: { fontSize: 13, color: "#64748B", lineHeight: 20, flex: 1 },
});
