import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {},
  item: { flexDirection: "row", marginBottom: 28 },
  indicator: { alignItems: "center", marginRight: 20, width: 22 },
  dotWrapper: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(99,102,241,0.15)",
    borderWidth: 2,
    borderColor: "#6366F1",
    alignItems: "center",
    justifyContent: "center",
  },
  dotWrapperEducation: {
    borderColor: "#A78BFA",
    backgroundColor: "rgba(167,139,250,0.15)",
  },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#6366F1" },
  dotEducation: { backgroundColor: "#A78BFA" },
  line: {
    width: 2,
    flex: 1,
    backgroundColor: "rgba(99,102,241,0.12)",
    marginTop: 4,
    marginBottom: -8,
  },
  card: {
    flex: 1,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.1)",
    borderRadius: 18,
    padding: 22,
    marginBottom: 4,
    backgroundColor: "rgba(15,20,40,0.7)",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
    flexWrap: "wrap",
    gap: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: "800",
    color: "#F1F5F9",
    flex: 1,
    letterSpacing: -0.3,
  },
  dateBadge: {
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  dateBadgeEducation: {
    backgroundColor: "rgba(167,139,250,0.1)",
    borderColor: "rgba(167,139,250,0.2)",
  },
  date: { fontSize: 12, color: "#A5B4FC", fontWeight: "600" },
  dateEducation: { color: "#C4B5FD" },
  organization: {
    fontSize: 14,
    fontWeight: "700",
    color: "#818CF8",
    marginBottom: 4,
  },
  organizationEducation: { color: "#A78BFA" },
  location: { fontSize: 12, color: "#475569", marginBottom: 10 },
  description: {
    fontSize: 14,
    color: "#94A3B8",
    lineHeight: 22,
    marginBottom: 12,
  },
  highlights: { gap: 6 },
  highlight: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  highlightBullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#6366F1",
    marginTop: 7,
    flexShrink: 0,
  },
  highlightBulletEducation: { backgroundColor: "#A78BFA" },
  highlightText: { fontSize: 13, color: "#64748B", lineHeight: 20, flex: 1 },
});
