import { StyleSheet } from "react-native";
import { aurora } from "@/lib/constants/aurora";

export default StyleSheet.create({
  container: {
    borderRadius: 16,
    backgroundColor: aurora.surfaceDark.value,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: aurora.borderSubtle.value,
  },
  imageWrapper: { position: "relative", overflow: "hidden" },
  typeBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: `${aurora.deepSpace.value}cc`,
    borderWidth: 1,
    borderColor: aurora.borderSubtle.value,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: aurora.auroraGreen.value,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  featuredBadgeTop: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: `${aurora.auroraGreen.value}20`,
    borderWidth: 1,
    borderColor: `${aurora.auroraGreen.value}40`,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  featuredBadgeTopText: {
    fontSize: 10,
    fontWeight: "700",
    color: aurora.auroraGreen.value,
  },
  content: { padding: 16 },
  title: {
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 6,
    color: aurora.starWhite.value,
    letterSpacing: -0.3,
  },
  description: {
    fontSize: 13,
    color: aurora.textSecondary.value,
    marginBottom: 12,
    lineHeight: 20,
  },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginBottom: 12 },
  tag: {
    backgroundColor: `${aurora.borderSubtle.value}80`,
    borderWidth: 1,
    borderColor: aurora.borderSubtle.value,
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tagText: {
    fontSize: 11,
    fontWeight: "600",
    color: aurora.textSecondary.value,
  },
  tagOverflow: {
    backgroundColor: `${aurora.nebulaPurple.value}20`,
    borderWidth: 1,
    borderColor: `${aurora.nebulaPurple.value}40`,
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tagOverflowText: {
    fontSize: 11,
    fontWeight: "600",
    color: aurora.nebulaPurple.value,
  },
  footer: {
    flexDirection: "row",
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: aurora.borderSubtle.value,
    flexWrap: "wrap",
  },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: aurora.borderSubtle.value,
  },
  actionBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: aurora.textSecondary.value,
  },
  viewLink: {
    fontSize: 13,
    fontWeight: "700",
    color: aurora.auroraGreen.value,
  },
  featuredBadge: {
    backgroundColor: `${aurora.auroraGreen.value}15`,
    borderWidth: 1,
    borderColor: `${aurora.auroraGreen.value}30`,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  featuredText: {
    fontSize: 11,
    fontWeight: "600",
    color: aurora.auroraGreen.value,
  },
});
