import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    borderRadius: 20,
    backgroundColor: "rgba(15,20,40,0.85)",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
  },
  imageWrapper: { position: "relative", overflow: "hidden" },
  typeBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(6,11,24,0.85)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.25)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#A5B4FC",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  content: { padding: 18 },
  title: {
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 6,
    color: "#F1F5F9",
    letterSpacing: -0.3,
  },
  description: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 14,
    lineHeight: 20,
  },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 14 },
  tag: {
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tagText: { fontSize: 11, fontWeight: "600", color: "#A5B4FC" },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.04)",
  },
  viewLink: { fontSize: 13, fontWeight: "700", color: "#818CF8" },
  featuredBadge: {
    backgroundColor: "rgba(234,179,8,0.1)",
    borderWidth: 1,
    borderColor: "rgba(234,179,8,0.2)",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  featuredText: { fontSize: 11, fontWeight: "600", color: "#FCD34D" },
});
