import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { alignItems: "center", paddingVertical: 28 },
  controls: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
    alignItems: "center",
  },
  orientationButton: {
    backgroundColor: "rgba(15,20,40,0.9)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orientationButtonText: { fontSize: 13, fontWeight: "600", color: "#94A3B8" },
  orientationIcon: { fontSize: 14 },
  deviceFrame: {
    backgroundColor: "#111827",
    borderRadius: 44,
    borderWidth: 3,
    borderColor: "#1F2937",
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.6,
    shadowRadius: 48,
    elevation: 24,
  },
  deviceFrameLandscape: { borderRadius: 30 },
  deviceScreen: {
    backgroundColor: "#000",
    borderRadius: 30,
    overflow: "hidden",
  },
  deviceScreenLandscape: { borderRadius: 22 },
  notch: {
    height: 28,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginBottom: 2,
  },
  notchBar: {
    width: 80,
    height: 6,
    backgroundColor: "#1F2937",
    borderRadius: 3,
  },
  iframeWrapper: { backgroundColor: "#fff" },
  homeBar: {
    height: 22,
    backgroundColor: "#111827",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  homeBarIndicator: {
    width: 100,
    height: 4,
    backgroundColor: "#374151",
    borderRadius: 2,
  },
  fallbackPanel: {
    padding: 28,
    alignItems: "center",
    gap: 16,
    backgroundColor: "rgba(10,14,30,0.95)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
    maxWidth: 320,
  },
  fallbackTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#F1F5F9",
    textAlign: "center",
  },
  fallbackText: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
  },
  qrPlaceholder: {
    width: 120,
    height: 120,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  qrText: {
    fontSize: 11,
    color: "#0F172A",
    textAlign: "center",
    fontWeight: "600",
  },
  downloadLinks: { flexDirection: "row", gap: 12 },
  downloadButton: {
    backgroundColor: "rgba(15,20,40,0.9)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  downloadButtonText: { fontSize: 12, fontWeight: "600", color: "#94A3B8" },
});
