import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { alignItems: "center", paddingVertical: 24 },
  controls: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
    alignItems: "center",
  },
  orientationButton: {
    backgroundColor: "rgba(30,41,59,0.8)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orientationButtonText: { fontSize: 13, fontWeight: "500", color: "#94A3B8" },
  orientationIcon: { fontSize: 14 },
  deviceFrame: {
    backgroundColor: "#1E293B",
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#334155",
    padding: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.5,
    shadowRadius: 40,
    elevation: 20,
  },
  deviceFrameLandscape: { borderRadius: 28 },
  deviceScreen: {
    backgroundColor: "#000",
    borderRadius: 28,
    overflow: "hidden",
  },
  deviceScreenLandscape: { borderRadius: 20 },
  notch: {
    height: 28,
    backgroundColor: "#1E293B",
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginBottom: 2,
  },
  notchBar: {
    width: 80,
    height: 6,
    backgroundColor: "#334155",
    borderRadius: 3,
  },
  iframeWrapper: { backgroundColor: "#fff" },
  homeBar: {
    height: 20,
    backgroundColor: "#1E293B",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  homeBarIndicator: {
    width: 100,
    height: 4,
    backgroundColor: "#475569",
    borderRadius: 2,
  },
  fallbackPanel: {
    padding: 24,
    alignItems: "center",
    gap: 16,
    backgroundColor: "rgba(15,23,42,0.9)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    maxWidth: 320,
  },
  fallbackTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#F1F5F9",
    textAlign: "center",
  },
  fallbackText: {
    fontSize: 13,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
  },
  qrPlaceholder: {
    width: 120,
    height: 120,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  qrText: {
    fontSize: 11,
    color: "#0F172A",
    textAlign: "center",
    fontWeight: "600",
  },
  downloadLinks: { flexDirection: "row", gap: 12 },
  downloadButton: {
    backgroundColor: "rgba(30,41,59,0.8)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  downloadButtonText: { fontSize: 12, fontWeight: "600", color: "#94A3B8" },
});
