import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 44,
    maxWidth: 1000,
    width: "100%",
    alignSelf: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 64,
  },
  loadingText: { fontSize: 16 },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 64,
  },
  errorText: { fontSize: 16 },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 28,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    backgroundColor: "rgba(99,102,241,0.06)",
  },
  backText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#818CF8",
  },
  thumbnail: {
    width: "100%",
    height: 340,
    borderRadius: 20,
    marginBottom: 36,
  },
  typeBadge: {
    alignSelf: "flex-start",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.3)",
    backgroundColor: "rgba(99,102,241,0.08)",
  },
  typeBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#A5B4FC",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  title: {
    fontSize: 40,
    fontWeight: "900",
    marginBottom: 14,
    letterSpacing: -1,
  },
  description: {
    fontSize: 17,
    lineHeight: 30,
    marginBottom: 36,
  },
  section: { marginBottom: 36 },
  sectionHeading: {
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 16,
    letterSpacing: -0.4,
  },
  technologies: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  techBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    backgroundColor: "rgba(99,102,241,0.08)",
  },
  techBadgeText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#A5B4FC",
  },
  gallery: { gap: 14 },
  galleryImage: {
    width: "100%",
    height: 240,
    borderRadius: 16,
  },
  links: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  link: {
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.3)",
    backgroundColor: "rgba(99,102,241,0.06)",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  linkText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#818CF8",
  },
});
