import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0F172A" },
  containerLight: { backgroundColor: "#F8FAFC" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(15,23,42,0.85)",
  },
  headerLight: {
    backgroundColor: "rgba(248,250,252,0.9)",
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  logoDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#3B82F6",
  },
  logo: {
    fontSize: 20,
    fontWeight: "800",
    color: "#F8FAFC",
    letterSpacing: -0.5,
  },
  logoDark: { color: "#0F172A" },
  nav: { flexDirection: "row", alignItems: "center", gap: 4 },
  main: { flex: 1 },
  mainContent: { flexGrow: 1 },
  footer: {
    paddingVertical: 32,
    paddingHorizontal: 32,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(15,23,42,0.9)",
  },
  footerLight: {
    backgroundColor: "#F1F5F9",
    borderTopColor: "rgba(0,0,0,0.06)",
  },
  footerInner: {
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
  },
  footerLeft: {},
  footerText: { fontSize: 14, color: "#475569" },
  footerTextLight: { color: "#64748B" },
  footerTagline: { fontSize: 12, color: "#334155", marginTop: 2 },
  footerRight: { flexDirection: "row", gap: 24 },
  footerLink: { fontSize: 13, color: "#475569" },
});
