import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#060B18",
  },
  containerLight: {
    backgroundColor: "#F0F4FF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
    backgroundColor: "rgba(6,11,24,0.92)",
  },
  headerLight: {
    backgroundColor: "rgba(240,244,255,0.95)",
    borderBottomColor: "rgba(99,102,241,0.1)",
  },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  logoDot: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#6366F1",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    fontSize: 18,
    fontWeight: "800",
    color: "#F1F5F9",
    letterSpacing: -0.5,
  },
  logoDark: { color: "#1E1B4B" },
  nav: { flexDirection: "row", alignItems: "center", gap: 2 },
  main: { flex: 1 },
  mainContent: { flexGrow: 1 },
  footer: {
    paddingVertical: 36,
    paddingHorizontal: 40,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
    backgroundColor: "rgba(6,11,24,0.95)",
  },
  footerLight: {
    backgroundColor: "#E8EEFF",
    borderTopColor: "rgba(99,102,241,0.1)",
  },
  footerInner: {
    maxWidth: 1200,
    width: "100%",
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
  },
  footerLeft: {},
  footerText: { fontSize: 13, color: "#475569" },
  footerTextLight: { color: "#6366F1" },
  footerTagline: {
    fontSize: 11,
    color: "#334155",
    marginTop: 3,
    letterSpacing: 0.3,
  },
  footerRight: { flexDirection: "row", gap: 28 },
  footerLink: { fontSize: 13, color: "#6366F1", fontWeight: "500" },
});
