import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    paddingVertical: 56,
    paddingHorizontal: 24,
    maxWidth: 680,
    width: "100%" as unknown as number,
    alignSelf: "center",
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: "700",
    color: "#818CF8",
    textAlign: "center",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  heading: {
    fontSize: 40,
    fontWeight: "900",
    color: "#F1F5F9",
    marginBottom: 10,
    textAlign: "center",
    letterSpacing: -1,
  },
  subheading: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 44,
    lineHeight: 26,
  },
  card: {
    backgroundColor: "rgba(15,20,40,0.7)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
    borderRadius: 24,
    padding: 36,
  },
  row: { flexDirection: "row", gap: 16 },
  fieldWrapper: { flex: 1, marginBottom: 20 },
  label: {
    fontSize: 11,
    fontWeight: "700",
    color: "#64748B",
    marginBottom: 8,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "rgba(6,11,24,0.7)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.15)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 15,
    color: "#F1F5F9",
  },
  inputFocused: { borderColor: "#6366F1" },
  inputError: { borderColor: "#EF4444" },
  textArea: { minHeight: 130, textAlignVertical: "top", paddingTop: 13 },
  errorText: { fontSize: 12, color: "#EF4444", marginTop: 4 },
  submitButton: {
    backgroundColor: "#6366F1",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 8,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  submitDisabled: { opacity: 0.55, shadowOpacity: 0 },
  submitText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  successBanner: {
    backgroundColor: "rgba(34,197,94,0.08)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.2)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    alignItems: "center",
  },
  successText: { fontSize: 14, color: "#4ADE80", fontWeight: "600" },
});
