import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    paddingVertical: 48,
    paddingHorizontal: 24,
    maxWidth: 640,
    width: "100%" as unknown as number,
    alignSelf: "center",
  },
  eyebrow: {
    fontSize: 13,
    fontWeight: "600",
    color: "#3B82F6",
    textAlign: "center",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  heading: {
    fontSize: 36,
    fontWeight: "800",
    color: "#F8FAFC",
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subheading: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 40,
    lineHeight: 24,
  },
  card: {
    backgroundColor: "rgba(30,41,59,0.6)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    padding: 32,
  },
  row: { flexDirection: "row", gap: 16 },
  fieldWrapper: { flex: 1, marginBottom: 20 },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#94A3B8",
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: "rgba(15,23,42,0.6)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#F1F5F9",
  },
  inputFocused: { borderColor: "#3B82F6" },
  inputError: { borderColor: "#EF4444" },
  textArea: { minHeight: 120, textAlignVertical: "top", paddingTop: 12 },
  errorText: { fontSize: 12, color: "#EF4444", marginTop: 4 },
  submitButton: {
    backgroundColor: "#2563EB",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  submitDisabled: { opacity: 0.6, shadowOpacity: 0 },
  submitText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },
  successBanner: {
    backgroundColor: "rgba(34,197,94,0.1)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.2)",
    borderRadius: 10,
    padding: 14,
    marginBottom: 20,
    alignItems: "center",
  },
  successText: { fontSize: 14, color: "#4ADE80", fontWeight: "500" },
});
