import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    minHeight: 600,
    paddingVertical: 80,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#0F172A",
  },
  glow1: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: "#2563EB",
    opacity: 0.15,
    top: -100,
    left: -100,
  },
  glow2: {
    position: "absolute",
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: "#7C3AED",
    opacity: 0.12,
    bottom: -80,
    right: -80,
  },
  glow3: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "#06B6D4",
    opacity: 0.08,
    top: "50%",
    left: "50%",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(37,99,235,0.15)",
    borderWidth: 1,
    borderColor: "rgba(37,99,235,0.3)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginBottom: 24,
    gap: 6,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: "rgba(59,130,246,0.4)",
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22C55E",
  },
  badgeText: { fontSize: 13, color: "#93C5FD", fontWeight: "500" },
  greeting: {
    fontSize: 18,
    color: "#94A3B8",
    marginBottom: 8,
    textAlign: "center",
    fontWeight: "400",
  },
  title: {
    fontSize: 56,
    fontWeight: "800",
    color: "#F8FAFC",
    textAlign: "center",
    marginBottom: 8,
    lineHeight: 64,
    letterSpacing: -1,
  },
  titleAccent: { color: "#3B82F6" },
  subtitle: {
    fontSize: 28,
    fontWeight: "600",
    color: "#7C3AED",
    textAlign: "center",
    marginBottom: 20,
  },
  description: {
    fontSize: 18,
    color: "#94A3B8",
    textAlign: "center",
    maxWidth: 600,
    lineHeight: 30,
    marginBottom: 40,
  },
  ctaRow: {
    flexDirection: "row",
    gap: 16,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 48,
  },
  ctaPrimary: {
    backgroundColor: "#2563EB",
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: "#2563EB",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  ctaPrimaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
  ctaSecondary: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 12,
  },
  ctaSecondaryText: { color: "#F8FAFC", fontSize: 16, fontWeight: "600" },
  statsRow: {
    flexDirection: "row",
    gap: 32,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  stat: { alignItems: "center" },
  statNumber: { fontSize: 32, fontWeight: "800", color: "#F8FAFC" },
  statLabel: { fontSize: 13, color: "#64748B", marginTop: 2 },
  scrollIndicator: { position: "absolute", bottom: 24, alignItems: "center" },
  scrollText: { fontSize: 12, color: "#475569", marginBottom: 4 },
  scrollArrow: { fontSize: 16, color: "#475569" },
});
