import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    minHeight: 680,
    paddingVertical: 100,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#060B18",
  },
  glow1: {
    position: "absolute",
    width: 600,
    height: 600,
    borderRadius: 300,
    backgroundColor: "#4F46E5",
    opacity: 0.12,
    top: -150,
    left: -150,
  },
  glow2: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: "#7C3AED",
    opacity: 0.1,
    bottom: -100,
    right: -100,
  },
  glow3: {
    position: "absolute",
    width: 350,
    height: 350,
    borderRadius: 175,
    backgroundColor: "#06B6D4",
    opacity: 0.07,
    top: "40%",
    left: "45%",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(99,102,241,0.12)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.3)",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 7,
    marginBottom: 32,
    gap: 8,
  },
  avatar: {
    width: 128,
    height: 128,
    borderRadius: 64,
    marginBottom: 24,
    borderWidth: 3,
    borderColor: "rgba(99,102,241,0.5)",
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22C55E",
  },
  badgeText: {
    fontSize: 13,
    color: "#A5B4FC",
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  greeting: {
    fontSize: 18,
    color: "#94A3B8",
    marginBottom: 8,
    textAlign: "center",
    fontWeight: "400",
    letterSpacing: 0.5,
  },
  title: {
    fontSize: 64,
    fontWeight: "900",
    color: "#F1F5F9",
    textAlign: "center",
    marginBottom: 10,
    lineHeight: 72,
    letterSpacing: -2,
  },
  titleAccent: { color: "#818CF8" },
  subtitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#A78BFA",
    textAlign: "center",
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  description: {
    fontSize: 17,
    color: "#94A3B8",
    textAlign: "center",
    maxWidth: 580,
    lineHeight: 28,
    marginBottom: 44,
  },
  ctaRow: {
    flexDirection: "row",
    gap: 14,
    flexWrap: "wrap",
    justifyContent: "center",
    marginBottom: 56,
  },
  ctaPrimary: {
    backgroundColor: "#6366F1",
    paddingHorizontal: 32,
    paddingVertical: 15,
    borderRadius: 14,
    shadowColor: "#6366F1",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  ctaPrimaryText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  ctaSecondary: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 32,
    paddingVertical: 15,
    borderRadius: 14,
  },
  ctaSecondaryText: { color: "#E2E8F0", fontSize: 16, fontWeight: "600" },
  statsRow: {
    flexDirection: "row",
    gap: 40,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  stat: { alignItems: "center" },
  statNumber: {
    fontSize: 34,
    fontWeight: "900",
    color: "#F1F5F9",
    letterSpacing: -1,
  },
  statLabel: {
    fontSize: 12,
    color: "#64748B",
    marginTop: 3,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  scrollIndicator: { position: "absolute", bottom: 24, alignItems: "center" },
  scrollText: { fontSize: 12, color: "#475569", marginBottom: 4 },
  scrollArrow: { fontSize: 16, color: "#475569" },
});
