import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { paddingVertical: 88, paddingHorizontal: 24 },
  inner: { maxWidth: 1100, width: "100%", alignSelf: "center" },
  eyebrow: {
    fontSize: 12,
    fontWeight: "700",
    color: "#818CF8",
    textAlign: "center",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 14,
  },
  heading: {
    fontSize: 40,
    fontWeight: "900",
    color: "#F1F5F9",
    marginBottom: 14,
    textAlign: "center",
    letterSpacing: -1,
  },
  subheading: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 52,
    lineHeight: 26,
    maxWidth: 520,
    alignSelf: "center",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "center",
  },
  card: {
    backgroundColor: "rgba(15,20,40,0.8)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.12)",
    borderRadius: 20,
    padding: 26,
    minWidth: 220,
    flex: 1,
    maxWidth: 280,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 18,
  },
  cardIcon: { fontSize: 26 },
  categoryTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#F1F5F9",
    letterSpacing: -0.3,
  },
  skills: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  skillBadge: {
    backgroundColor: "rgba(99,102,241,0.1)",
    borderWidth: 1,
    borderColor: "rgba(99,102,241,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  skillText: { fontSize: 12, fontWeight: "600", color: "#A5B4FC" },
});
