import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { paddingVertical: 80, paddingHorizontal: 24 },
  inner: { maxWidth: 1100, width: "100%", alignSelf: "center" },
  eyebrow: {
    fontSize: 13,
    fontWeight: "600",
    color: "#3B82F6",
    textAlign: "center",
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  heading: {
    fontSize: 36,
    fontWeight: "800",
    color: "#F8FAFC",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subheading: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginBottom: 48,
    lineHeight: 24,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "center",
  },
  card: {
    backgroundColor: "rgba(30,41,59,0.8)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    padding: 24,
    minWidth: 220,
    flex: 1,
    maxWidth: 280,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  cardIcon: { fontSize: 24 },
  categoryTitle: { fontSize: 16, fontWeight: "700", color: "#F1F5F9" },
  skills: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  skillBadge: {
    backgroundColor: "rgba(59,130,246,0.1)",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  skillText: { fontSize: 12, fontWeight: "500", color: "#93C5FD" },
});
